#
# (C) Copyright 2012 Henrik Nordstrom <henrik@henriknordstrom.net>
#
# Based on some other Makefile
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += cpu_info.o
obj-y += sdram.o
obj-$(CONFIG_SMARTCHIP_SCA200V100) += sca200v100/
obj-$(CONFIG_SMARTCHIP_SCA200V200) += sca200v200/
