/* Copyright (C) 2016 Cadence Design Systems.  All rights reserved           */
/* THIS FILE IS AUTOMATICALLY GENERATED BY CADENCE BLUEPRINT, DO NOT EDIT    */
/*                                                                           */

#ifndef __REG_CDNSTCPC_MAP_H__
#define __REG_CDNSTCPC_MAP_H__

#include <linux/module.h>
#include <linux/usb/tcpm.h>
#include <linux/interrupt.h>
#include <linux/platform_device.h>

#include <linux/io.h>
#include <linux/of.h>
#include <linux/of_platform.h>

#include <linux/firmware.h>
#include <linux/extcon.h>

#include <linux/usb/otg.h>

#include "cdnstcpc_map_macro.h"

#define CONFIG_USB_PD_PORT_COUNT                1

struct cdnstcpc_regprof {
	volatile uint32_t VENDOR_ID;                    /*        0x0 - 0x4        */
	volatile uint32_t PRODUCT_ID;                   /*        0x4 - 0x8        */
	volatile uint32_t DEVICE_ID;                    /*        0x8 - 0xc        */
	volatile uint32_t USBTYPEC_REV;                 /*        0xc - 0x10       */
	volatile uint32_t USBPD_REV_VER;                /*       0x10 - 0x14       */
	volatile uint32_t PD_INTERFACE_REV;             /*       0x14 - 0x18       */
	volatile uint32_t Reserved_01;                  /*       0x18 - 0x1c       */
	volatile uint32_t Reserved_02;                  /*       0x1c - 0x20       */
	volatile uint32_t ALERT;                        /*       0x20 - 0x24       */
	volatile uint32_t ALERT_MASK;                   /*       0x24 - 0x28       */
	volatile uint32_t POWER_STATUS_MASK;            /*       0x28 - 0x2c       */
	volatile uint32_t FAULT_STATUS_MASK;            /*       0x2c - 0x30       */
	volatile uint32_t Reserved_03;                  /*       0x30 - 0x34       */
	volatile uint32_t CONFIG_STANDARD_OUTPUT;       /*       0x34 - 0x38       */
	volatile uint32_t TCPC_CONTROL;                 /*       0x38 - 0x3c       */
	volatile uint32_t ROLE_CONTROL;                 /*       0x3c - 0x40       */
	volatile uint32_t FAULT_CONTROL;                /*       0x40 - 0x44       */
	volatile uint32_t POWER_CONTROL;                /*       0x44 - 0x48       */
	volatile uint32_t CC_STATUS;                    /*       0x48 - 0x4c       */
	volatile uint32_t POWER_STATUS;                 /*       0x4c - 0x50       */
	volatile uint32_t FAULT_STATUS;                 /*       0x50 - 0x54       */
	volatile uint32_t Reserved_04;                  /*       0x54 - 0x58       */
	volatile uint32_t Reserved_05;                  /*       0x58 - 0x5c       */
	volatile uint32_t COMMAND;                      /*       0x5c - 0x60       */
	volatile uint32_t DEVICE_CAPABILITIES_1;        /*       0x60 - 0x64       */
	volatile uint32_t DEVICE_CAPABILITIES_2;        /*       0x64 - 0x68       */
	volatile uint32_t STANDARD_INPUT_CAPABILITIES;  /*       0x68 - 0x6c       */
	volatile uint32_t STANDARD_OUTPUT_CAPABILITIES; /*       0x6c - 0x70       */
	volatile uint32_t Reserved_06;                  /*       0x70 - 0x74       */
	volatile uint32_t Reserved_07;                  /*       0x74 - 0x78       */
	volatile uint32_t Reserved_08;                  /*       0x78 - 0x7c       */
	volatile uint32_t MESSAGE_HEADER_INFO;          /*       0x7c - 0x80       */
	volatile uint32_t RECEIVE_DETECT;               /*       0x80 - 0x84       */
	volatile uint32_t RECEIVE_BYTE_COUNT;           /*       0x84 - 0x88       */
	volatile uint32_t RX_BUF_FRAME_TYPE;            /*       0x88 - 0x8c       */
	volatile uint32_t RX_BUF_HEADER_BYTE_10;        /*       0x8c - 0x90       */
	volatile uint32_t RX_BUF_OBJ1_BYTE_3210;        /*       0x90 - 0x94       */
	volatile uint32_t RX_BUF_OBJ2_BYTE_3210;        /*       0x94 - 0x98       */
	volatile uint32_t RX_BUF_OBJ3_BYTE_3210;        /*       0x98 - 0x9c       */
	volatile uint32_t RX_BUF_OBJ4_BYTE_3210;        /*       0x9c - 0xa0       */
	volatile uint32_t RX_BUF_OBJ5_BYTE_3210;        /*       0xa0 - 0xa4       */
	volatile uint32_t RX_BUF_OBJ6_BYTE_3210;        /*       0xa4 - 0xa8       */
	volatile uint32_t RX_BUF_OBJ7_BYTE_3210;        /*       0xa8 - 0xac       */
	volatile uint32_t TRANSMIT;                     /*       0xac - 0xb0       */
	volatile uint32_t TRANSMIT_BYTE_COUNT;          /*       0xb0 - 0xb4       */
	volatile uint32_t TX_BUF_HEADER_BYTE_10;        /*       0xb4 - 0xb8       */
	volatile uint32_t TX_BUF_OBJ1_BYTE_3210;        /*       0xb8 - 0xbc       */
	volatile uint32_t TX_BUF_OBJ2_BYTE_3210;        /*       0xbc - 0xc0       */
	volatile uint32_t TX_BUF_OBJ3_BYTE_3210;        /*       0xc0 - 0xc4       */
	volatile uint32_t TX_BUF_OBJ4_BYTE_3210;        /*       0xc4 - 0xc8       */
	volatile uint32_t TX_BUF_OBJ5_BYTE_3210;        /*       0xc8 - 0xcc       */
	volatile uint32_t TX_BUF_OBJ6_BYTE_3210;        /*       0xcc - 0xd0       */
	volatile uint32_t TX_BUF_OBJ7_BYTE_3210;        /*       0xd0 - 0xd4       */
	volatile uint32_t VBUS_VOLTAGE;                 /*       0xd4 - 0xd8       */
	volatile uint32_t VBUS_SINK_DISCONNECT_THRESHOLD;
	/*       0xd8 - 0xdc       */
	volatile uint32_t VBUS_STOP_DISCHARGE_THRESHOLD;
	/*       0xdc - 0xe0       */
	volatile uint32_t VBUS_VOLTAGE_ALARM_HI_CFG;    /*       0xe0 - 0xe4       */
	volatile uint32_t VBUS_VOLTAGE_ALARM_LO_CFG;    /*       0xe4 - 0xe8       */
	volatile uint32_t Reserved_09;                  /*       0xe8 - 0xec       */
	volatile uint32_t Reserved_10;                  /*       0xec - 0xf0       */
	volatile uint32_t Reserved_11;                  /*       0xf0 - 0xf4       */
	volatile uint32_t RX_ERR_CNT;                   /*       0xf4 - 0xf8       */
	volatile uint32_t PHY_MUX_CTRL;                 /*       0xf8 - 0xfc       */
	volatile uint32_t CC_PD_TEST_DBG;               /*       0xfc - 0x100      */
	volatile uint32_t SFR_REG_0;                    /*      0x100 - 0x104      */
	volatile uint32_t SFR_REG_1;                    /*      0x104 - 0x108      */
	volatile uint32_t SFR_REG_2;                    /*      0x108 - 0x10c      */
};

struct cdnstcpc_map {
	struct cdnstcpc_regprof cdnstcpc_reg;           /*        0x0 - 0x10c      */
	volatile uint32_t SFR_REG_SPACE[61];            /*      0x10c - 0x200      */
	volatile char pad__0[0x7e00];                   /*      0x200 - 0x8000     */
	volatile uint32_t IRAM_REG_SPACE[4096];         /*     0x8000 - 0xc000     */
};

struct smartx_tcpc_notify {
	//unsigned char         cc;
	unsigned char         flip;
	unsigned char         data_role;
	//unsigned char         power_role;
	unsigned char         dp;
	unsigned char         usb;
};

struct smartx_tcpc;

typedef int (*smartx_tcpc_notifier_call)
(struct smartx_tcpc *tcpc, struct smartx_tcpc_notify new, int data);

struct smartx_tcpc {
	struct device       *dev;
	struct tcpc_dev     tcpc;
	struct tcpm_port    *tcpm;

	void __iomem        *tcpd_base;
	void __iomem        *user_define_base;

	struct extcon_dev   *extcon;
	struct smartx_tcpc_notify   notify;

	int                 irq;
	int                 mode;//usb:0 dp:1
	int                 cc1_gpio;
	int                 cc2_gpio;
	int                 typec_gpio;
	int                 port_index;
	enum usb_dr_mode    dr_mode;
	unsigned int        mode_cfg_reg;

	bool                is_dp_enabled;

	struct work_struct  usb_dp_switch_work;
	struct notifier_block   usb_dp_switch_nb;
	struct mutex        lock; /* device lock */

	int                 hpd_gpio;
};

int smartx_typec_common_phy_access(struct smartx_tcpc *tcpc, unsigned char flag);

int smartx_typec_set_config_mode(struct smartx_tcpc *tcpc);

#endif /* __REG_CDNSTCPC_MAP_H__ */
