# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2021 SmartChip Electronics Co., Ltd

obj-$(CONFIG_SMARTCHIP_SCA200V100) += pinctrl-sca200v100.o
obj-$(CONFIG_SMARTCHIP_SCA200V200) += pinctrl-sca200v200.o
