# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2021 SmartChip Electronics Co., Ltd
#

obj-$(CONFIG_SMARTCHIP_SCA200V100) += clk_sca200v100.o
obj-$(CONFIG_SMARTCHIP_SCA200V200) += clk_sca200v200.o
