/* Copyright (C) 2016 Cadence Design Systems.  All rights reserved           */
/* THIS FILE IS AUTOMATICALLY GENERATED BY CADENCE BLUEPRINT, DO NOT EDIT    */
/*                                                                           */

#ifndef __REG_USBSS_DRD_ADDR_MAP_H__
#define __REG_USBSS_DRD_ADDR_MAP_H__

#include "drd_regs_macro.h"

struct usbdrd_register_block_type {
	volatile uint32_t OTGCMD;                       /*        0x0 - 0x4        */
	volatile uint32_t OTGSTS;                       /*        0x4 - 0x8        */
	volatile uint32_t OTGSTATE;                     /*        0x8 - 0xc        */
	volatile uint32_t OTGREFCLK;                    /*        0xc - 0x10       */
	volatile uint32_t OTGIEN;                       /*       0x10 - 0x14       */
	volatile uint32_t OTGIVECT;                     /*       0x14 - 0x18       */
	volatile char pad__0[0x8];                      /*       0x18 - 0x20       */
	volatile uint32_t PAD2_18;                     /*       0x20 - 0x24       */
	volatile uint32_t PAD2_19;                       /*       0x24 - 0x28       */
	volatile char pad__1[0x8];                      /*       0x28 - 0x30       */
	volatile uint32_t OTGVERSION;                   /*       0x30 - 0x34       */
	volatile uint32_t OTGCAPABILITY;                /*       0x34 - 0x38       */
	volatile char pad__2[0x8];                      /*       0x38 - 0x40       */
	volatile uint32_t OTGSIMULATE;                  /*       0x40 - 0x44       */
	volatile char pad__3[0xc];                      /*       0x44 - 0x50       */
	volatile uint32_t PAD2_26;                    /*       0x50 - 0x54       */
	volatile uint32_t PAD2_27;                /*       0x54 - 0x58       */
	volatile uint32_t OTGCTRL1;                     /*       0x58 - 0x5c       */
	volatile uint32_t PAD2_29;                     /*       0x5c - 0x60       */
	volatile uint32_t TYPEC_CFG;                    /*       0x60 - 0x64       */
};

struct USBSS_DRD_addr_map {
	struct usbdrd_register_block_type usbdrd_register_block;
	/*        0x0 - 0x64       */
};

#endif /* __REG_USBSS_DRD_ADDR_MAP_H__ */
