obj-$(CONFIG_SMARTCHIP_ICC) += icc_smartchip.o
obj-$(CONFIG_SMARTCHIP_ICC) += icc.o
obj-$(CONFIG_SMARTCHIP_ICC) += icc_of.o
obj-$(CONFIG_SMARTCHIP_ICC) += icc_shm.o
obj-$(CONFIG_SMARTCHIP_ICC) += icc_spinlock.o
obj-$(CONFIG_SMARTCHIP_ICC) += icc_peer_cortex_a.o
obj-$(CONFIG_SMARTCHIP_ICC) += icc_peer_cortex_m.o
obj-$(CONFIG_SMARTCHIP_ICC) += icc_peer_ceva.o
