dtb-$(CONFIG_ARCH_SCA200V100) += smartchip-sca200v100-evb.dtb
dtb-$(CONFIG_ARCH_SCA200V100) += smartchip-sca200v100-bd2.dtb
dtb-$(CONFIG_ARCH_SCA200V100) += smartchip-sca200v100-bd2_box.dtb
dtb-$(CONFIG_ARCH_SCA200V100) += smartchip-sca200v100-bd3.dtb
dtb-$(CONFIG_ARCH_SCA200V100) += smartchip-sca200v100-bd4.dtb
dtb-$(CONFIG_ARCH_SCA200V100) += smartchip-sca200v100-bd4_hrcam.dtb
dtb-$(CONFIG_ARCH_SCA200V100) += smartchip-sca200v100-bd4_bodyai.dtb

dtb-$(CONFIG_ARCH_SCA200V100) += smartchip-sca200v102-bd1_fast.dtb

## sca200v200
dtb-$(CONFIG_ARCH_SCA200V200) += smartchip-sca200v200-evb.dtb
dtb-$(CONFIG_ARCH_SCA200V200) += smartchip-sca200v200-bd2.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
